baseURL = "https://jameshub.com/"
theme = "gokarna"
title = "whoami.exe"
languageCode = "en"
defaultContentLanguage = "en"
enableEmoji = true
enableRobotsTXT = true

[params]
  description = "Digital Forensics Student, Intelligence Analyst, currently @ getDarkTower"
  accentColor = "#EB67b2"
  metaKeywords = ["blog",  "hugo"]


[menu]

  [[menu.main]]
    identifier = "github"
    pre = "<img class='svg-inject' src='svg/icons/github.svg' />"
    url = "https://github.com/milkshakesbot"
    weight = 1

  [[menu.main]]
    identifier = "bluesky"
    pre = "<img class='svg-inject' src='svg/icons/bluesky.svg' />"
    url = "https://bsky.app/profile/milkshakes.bot"
    weight = 2

  [[menu.main]]
    identifier = "twitter"
    pre = "<img class='svg-inject' src='svg/icons/twitter.svg' />"
    url = "https://twitter.com/milkshakesbot"
    weight = 3

  [[menu.main]]
    identifier = "linkedin"
    pre = "<img class='svg-inject' src='svg/icons/linkedin.svg' />"
    url = "https://www.linkedin.com/in/hubnerj"
    weight = 4

  [[menu.main]]
    identifier = "mastodon"
    pre = "<img class='svg-inject' src='svg/icons/mastodon.svg' />"
    url = "https://infosec.exchange/@milkshakesbot"
    weight = 5

  [[menu.main]]
    identifier = "email"
    name = "Contact"
    url = "/contact/"
    weight = 6