languageCode = "en-us"
theme = "gokarna"
title = "whoami.exe"

[params]
  description = "Digital Forensics Student, Intelligence Analyst, currently @ getDarkTower"
  accentColor = "#EB67b2"
  metaKeywords = ["blog",  "hugo"]


[menu]

  [[menu.main]]
    identifier = "github"
    pre = "<span data-feather='github'></span>"
    url = "https://github.com/milkshakesbot"
    weight = 1

  [[menu.main]]
    identifier = "twitter"
    pre = "<span data-feather='twitter'></span>"
    url = "https://twitter.com/milkshakesbot"
    weight = 2

  [[menu.main]]
    identifier = "linkedin"
    pre = "<span data-feather='linkedin'></span>"
    url = "https://www.linkedin.com/in/hubnerj/t"
    weight = 3

  [[menu.main]]
    identifier = "mastodon"
    pre = "<span data-feather='shield'></span>"
    url = "https://infosec.exchange/@milkshakesbot"
    weight = 4

  [[menu.main]]
    identifier = "email"
    name = "Contact"
    url = "/contact/"
    weight = 5